# Generated by Django 5.1.3 on 2026-06-24 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('user_position', models.CharField(choices=[('찬성', '찬성'), ('반대', '반대')], max_length=8)),
                ('opponent_position', models.CharField(choices=[('찬성', '찬성'), ('반대', '반대')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(help_text='0-based turn order within the game.')),
                ('user_text', models.TextField(blank=True)),
                ('opponent_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='api.game')),
            ],
            options={
                'ordering': ['game', 'index'],
                'unique_together': {('game', 'index')},
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('user', 'user'), ('opponent', 'opponent')], max_length=8)),
                ('logical_consistency', models.PositiveSmallIntegerField()),
                ('relevance', models.PositiveSmallIntegerField()),
                ('creativity', models.PositiveSmallIntegerField()),
                ('rebuttal', models.PositiveSmallIntegerField()),
                ('summarization', models.PositiveSmallIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('raw', models.TextField(blank=True, help_text='Raw LLM scoring text, kept for auditing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.turn')),
            ],
            options={
                'unique_together': {('turn', 'side')},
            },
        ),
    ]
