# Generated by Django 5.1.3 on 2026-06-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('ethics', 'ethics'), ('tech', 'tech'), ('culture', 'culture'), ('random', 'random')], default='random', max_length=16),
        ),
        migrations.AddField(
            model_name='game',
            name='max_turns',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='game',
            name='opponent_persona',
            field=models.CharField(choices=[('logician', 'logician'), ('provocateur', 'provocateur'), ('socratic', 'socratic'), ('historical', 'historical')], default='provocateur', max_length=16),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('finished', 'finished')], default='active', max_length=8),
        ),
        migrations.AddField(
            model_name='score',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
