"""
Django settings for ArguMind project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR points to the Django backend root (the `backend/` directory).
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# REPO_ROOT points to the repository root (parent of `backend/`), where the
# `frontend/` directory lives. Used to locate the built React app.
REPO_ROOT = os.path.dirname(BASE_DIR)

# Load environment variables from backend/.env (see .env.example).
load_dotenv(os.path.join(BASE_DIR, '.env'))


def _env_bool(name, default=False):
    """Read a boolean-ish environment variable."""
    return os.getenv(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True for local dev; set DJANGO_DEBUG=False in production.
DEBUG = _env_bool('DJANGO_DEBUG', True)

# SECURITY WARNING: keep the secret key used in production secret!
# The key is read exclusively from the DJANGO_SECRET_KEY env var (see backend/.env);
# no secret is hardcoded in source. In DEBUG a missing key falls back to an
# ephemeral random key (fine for local dev); outside DEBUG it is a hard error.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = get_random_secret_key()
    else:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY environment variable must be set when DEBUG is False.'
        )

# Comma-separated list via DJANGO_ALLOWED_HOSTS, e.g. "example.com,api.example.com".
ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        'DJANGO_ALLOWED_HOSTS',
        'argumind.uitae.kim,localhost,127.0.0.1,0.0.0.0',
    ).split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
    'corsheaders',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # The LLM-backed endpoints are intentionally public (AllowAny) so the game
    # needs no login, but each call costs a Google AI request. Scoped rate limits
    # cap abuse/cost without breaking the anonymous flow. Override the rates via
    # the DRF_THROTTLE_* env vars.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'get_topic': os.getenv('DRF_THROTTLE_GET_TOPIC', '30/min'),
        'get_argument': os.getenv('DRF_THROTTLE_GET_ARGUMENT', '30/min'),
        'get_scores': os.getenv('DRF_THROTTLE_GET_SCORES', '60/min'),
        'game_read': os.getenv('DRF_THROTTLE_GAME_READ', '120/min'),
    },
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    'https://argumind.uitae.kim',
    'http://127.0.0.1',
    'http://localhost:3000',  # React 개발 서버
]

ROOT_URLCONF = 'ArguMind.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(REPO_ROOT, 'frontend', 'build')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ArguMind.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

# Only registered once the React app has been built, to avoid a staticfiles
# warning during backend-only development.
_FRONTEND_STATIC = os.path.join(REPO_ROOT, 'frontend', 'build', 'static')
STATICFILES_DIRS = [_FRONTEND_STATIC] if os.path.isdir(_FRONTEND_STATIC) else []

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
